# This project fundamentally depends on Linux cgroups via Firejail, and
# is currently only actively tested on 64-bit x86 targets, so silence
# warnings about transitive dependencies specific to other targets.
[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-DFS-2016"]

[bans]
multiple-versions = "allow"
wildcards = "deny"
deny = [
    { name = "serde_derive", version = ">=1.0.172, <1.0.184" }
]
